temperature_control_method: "occupancy"
ventilation_control_method: "co2_controlled"
battery_control_method: "demand_levelling"
open_window_co2: 800
close_window_co2: 650
comfort_temp_setpoint: 20
setback_temp_setpoint: 15
eval_frequency: 52560
eval_rollouts: 1