temperature_control: "constant"
ventilation_control: "co2_controlled"
battery_control: ""
open_window_co2: 800
close_window_co2: 500
comfort_temp_setpoint: 20
setback_temp_setpoint: 15
user_type_vent: "random"
user_type_temp: "random"
eval_frequency: 52560
eval_rollouts: 5