temperature_control_method: "switch_onoff"
ventilation_control_method: "Jones2017"
battery_control_method: "demand_levelling"
open_window_co2: 1000
close_window_co2: 500
comfort_temp_setpoint: 20
setback_temp_setpoint: 15
eval_frequency: 52560
eval_rollouts: 1