temperature_control_method: "occupancy"
ventilation_control_method: "co2_controlled"
battery_control_method: "excess_storage"
open_window_co2: 1000
close_window_co2: 500
comfort_temp_setpoint: 20
setback_temp_setpoint: 15
eval_frequency: 52560
eval_rollouts: 1