#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake-himem
#SBATCH --mem=3420
#SBATCH -N 1
#SBATCH -t 1:00:00
#SBATCH -J leiden-job
#SBATCH --array=0-5

source ~/.bashrc

PARAMS=(
"--wandb_tags sac full_test paper discount alpha --case 0 --year 2022 --rep 0 --emissions_weight 1 --algorithm sac --wandb_entity hannesg --wandb_project Leiden-paper --comfort_temp_setpoint 20 --setback_temp_setpoint 12 --discount 0.999  --critic_hidden_layers 2 --critic_hidden_dimension 256 --actor_hidden_layers 2 --actor_hidden_dimension 256  --map_setpoints_to_comfort_space True  --occupancy_schedule stochastic_occupancy --sleep_hours True --forecast_length 6  --normalise_observations True  --n_frame_stack 4 --discrete_actions True --temperature_weight 1 --init_temperature 0.1 --learnable_temperature True  --incremental_actions True --short_episode True"
"--wandb_tags sac full_test paper discount alpha --case 0 --year 2022 --rep 0 --emissions_weight 1 --algorithm sac --wandb_entity hannesg --wandb_project Leiden-paper --comfort_temp_setpoint 20 --setback_temp_setpoint 12 --discount 0.99  --critic_hidden_layers 2 --critic_hidden_dimension 256 --actor_hidden_layers 2 --actor_hidden_dimension 256  --map_setpoints_to_comfort_space True  --occupancy_schedule stochastic_occupancy --sleep_hours True --forecast_length 6  --normalise_observations True  --n_frame_stack 4 --discrete_actions True --temperature_weight 1 --init_temperature 0.1 --learnable_temperature True  --incremental_actions True --short_episode True"
"--wandb_tags sac full_test paper discount alpha --case 0 --year 2022 --rep 0 --emissions_weight 1 --algorithm sac --wandb_entity hannesg --wandb_project Leiden-paper --comfort_temp_setpoint 20 --setback_temp_setpoint 12 --discount 0.9  --critic_hidden_layers 2 --critic_hidden_dimension 256 --actor_hidden_layers 2 --actor_hidden_dimension 256  --map_setpoints_to_comfort_space True  --occupancy_schedule stochastic_occupancy --sleep_hours True --forecast_length 6  --normalise_observations True  --n_frame_stack 4 --discrete_actions True --temperature_weight 1 --init_temperature 0.1 --learnable_temperature True  --incremental_actions True --short_episode True"
"--wandb_tags sac full_test paper discount alpha --case 0 --year 2022 --rep 0 --emissions_weight 1 --algorithm sac --wandb_entity hannesg --wandb_project Leiden-paper --comfort_temp_setpoint 20 --setback_temp_setpoint 12 --discount 0.999  --critic_hidden_layers 2 --critic_hidden_dimension 256 --actor_hidden_layers 2 --actor_hidden_dimension 256  --map_setpoints_to_comfort_space True  --occupancy_schedule stochastic_occupancy --sleep_hours True --forecast_length 6  --normalise_observations True  --n_frame_stack 4 --discrete_actions True --temperature_weight 1 --init_temperature 0.0 --learnable_temperature False  --incremental_actions True --short_episode True"
"--wandb_tags sac full_test paper discount alpha --case 0 --year 2022 --rep 0 --emissions_weight 1 --algorithm sac --wandb_entity hannesg --wandb_project Leiden-paper --comfort_temp_setpoint 20 --setback_temp_setpoint 12 --discount 0.99  --critic_hidden_layers 2 --critic_hidden_dimension 256 --actor_hidden_layers 2 --actor_hidden_dimension 256  --map_setpoints_to_comfort_space True  --occupancy_schedule stochastic_occupancy --sleep_hours True --forecast_length 6  --normalise_observations True  --n_frame_stack 4 --discrete_actions True --temperature_weight 1 --init_temperature 0.0 --learnable_temperature False  --incremental_actions True --short_episode True"
"--wandb_tags sac full_test paper discount alpha --case 0 --year 2022 --rep 0 --emissions_weight 1 --algorithm sac --wandb_entity hannesg --wandb_project Leiden-paper --comfort_temp_setpoint 20 --setback_temp_setpoint 12 --discount 0.9  --critic_hidden_layers 2 --critic_hidden_dimension 256 --actor_hidden_layers 2 --actor_hidden_dimension 256  --map_setpoints_to_comfort_space True  --occupancy_schedule stochastic_occupancy --sleep_hours True --forecast_length 6  --normalise_observations True  --n_frame_stack 4 --discrete_actions True --temperature_weight 1 --init_temperature 0.0 --learnable_temperature False --incremental_actions True --short_episode True"

 )

singularity run cubes-cluster.simg python3.9 main_leiden.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
