#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 01:00:00
#SBATCH -J p-jjjl-final-v4
#SBATCH --array=0-5  # Adjust array for 6 jobs (2 zones * 3 heating patterns)

source ~/.bashrc

# Define the PARAMS array dynamically:
# Zone 0 and Zone 9: 3 heating patterns, 1 temperature (20°C), 1 rep -> 3 * 2 = 6 jobs
PARAMS=()
zones=(0 9)  # Zones 0 and 9
heating_patterns=("once" "twice" "thrice")  # Three heating patterns

for z in "${zones[@]}"
do
    for pattern in "${heating_patterns[@]}"
    do
        # Fixed temp to 20 and rep to 1
        PARAMS+=("--exp_typ thermostat --zone $z --heating_pattern $pattern --algorithm rbc --case 0 --rep 1 --wandb_name testing_all_heating --wandb_tags testing_all_heating --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60")
    done
done

# Run the job with singularity using the task ID as an index for PARAMS
singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
