#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=3420
#SBATCH -N 1
#SBATCH -t 12:00:00
#SBATCH -J p-jjjl-obs
#SBATCH --array=0-1

source ~/.bashrc

PARAMS=(
"--wandb_tags parsons rbc  --case 0 --year 2022 --rep 0 --emissions_weight 1 --algorithm rbc --rbc_switch 0 --wandb_entity jjjl4 --wandb_project jack-observations --comfort_temp_setpoint 20 --setback_temp_setpoint 12 --reward_function_type Linear --timesteps_per_hour 6 --occupancy_schedule stochastic_occupancy --sleep_hours True --map_setpoints_to_comfort_space False"
"--wandb_tags parsons sav  --case 0 --year 2022 --rep 0 --emissions_weight 1 --algorithm sac --rbc_switch 0 --wandb_entity jjjl4 --wandb_project jack-observations --comfort_temp_setpoint 20 --setback_temp_setpoint 12 --reward_function_type Linear --timesteps_per_hour 6 --occupancy_schedule stochastic_occupancy --sleep_hours True --map_setpoints_to_comfort_space False"
 )

singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
