#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 01:00:00
#SBATCH -J p-jjjl-SYNTHETHIC
#SBATCH --array=0-30

source ~/.bashrc

# Define the PARAMS array dynamically for 2 zones and 15 cases (2 * 15 = 30 jobs)
PARAMS=()
for z in 0 9
do
    for c in {0..14}  # Cases from 0 to 14 (15 cases)
    do
            PARAMS+=("--exp_typ thermostat --zone $z --heating_pattern twice --algorithm rbc --case $c --rep 1 --wandb_name testing_all_heating --wandb_tags testing_all_heating --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60")
    done
done

# Run the job with singularity using the task ID as an index for PARAMS
singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
