#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 00:30:00
#SBATCH -J p-jjjl-SYNTHETHIC
#SBATCH --array=0-3  # Adjust array for 4 jobs (5, 10, 15, 30 inactivity values)

source ~/.bashrc

# Define the PARAMS array for zone 9, and different inactivity_threshold values
PARAMS=()
z=9  # Set zone to 9
c=0  # Set case to 0
for inactivity in 5 10 15 30
do
    PARAMS+=("--exp_typ thermostat --zone $z --heating_pattern twice --inactivity_threshold $inactivity --algorithm rbc --rbc_switch 2 --case $c --rep 1 --wandb_name thernostat_test_run --wandb_tags thermostat test --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60")
done

# Run the job with singularity using the task ID as an index for PARAMS
singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
