#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 00:30:00
#SBATCH -J p-jjjl-new-model
#SBATCH --array=0-1

source ~/.bashrc

PARAMS=()
zones=(0 9)

for z in "${zones[@]}"
do
    PARAMS+=("--exp_typ thermostat --zone $z --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name thermostat_final_v7 --wandb_tags thermostat_final_v7-5 --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --inactivity_threshold 30 --no_ventilation True --holiday False")
done

singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
