#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 1:00:00
#SBATCH -J p-jjjl-cost
#SBATCH --array=0

source ~/.bashrc

PARAMS=(
    "--exp_type thermostat --zone 9 --heating_set_temp_seed 42 --heating_on_off_seed 42 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name testing_12_setback --wandb_tags rbc final paper2 --year 2022 --comfort_temp_setpoint 20 --setback_temp_setpoint 12 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"

)


singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
