#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 01:00:00
#SBATCH -J p-jjjl-SYNTHETHIC
#SBATCH --array=0-21

source ~/.bashrc

# Define the PARAMS array dynamically for 2 zones and 11 reps (2 * 11 = 22 jobs)
PARAMS=()
for z in 0 9
do
    for r in {0..10}  # Reps from 0 to 10 (11 reps)
    do
        PARAMS+=("--exp_type SI --zone $z --algorithm rbc --rbc_switch 2 --case 0 --rep $r --wandb_name SI_Synthetic_Occupancy_Test --wandb_tags SI synthetic occupancy --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60")
    done
done

# Run the job with singularity using the task ID as an index for PARAMS
singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
