#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=3370
#SBATCH -N 1
#SBATCH -t 00:45:00
#SBATCH -J p-jjjl-h28
#SBATCH --array=0-1

source ~/.bashrc




PARAMS=(
    --exp_type supplementary_h28 --zone 0 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name SI_H28_Test_Run --wandb_tags rbc SI --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True
    --exp_type supplementary_h28 --zone 9 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name SI_H28_Test_Run --wandb_tags rbc SI --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True
    )



singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}