#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 01:00:00
#SBATCH -J p-jjjl-final-v5
#SBATCH --array=5,6,7,14,15,16,36,38,47

source ~/.bashrc

# Define the PARAMS array dynamically:
PARAMS=()
zones=(0 9)  # Zones 0 and 9
heating_patterns_zone_0=("once" "twice" "thrice")  # Three heating patterns for zone 0
heating_patterns_zone_9=("once")  # Only 'once' for zone 9
temperatures=(19 20 21)  # Temperature range
cases=(0)  # Only case 0
reps=("H43" "H09" "H11" "H33" "H30")  # Reps excluding H28

for rep in "${reps[@]}"
do
    for z in "${zones[@]}"
    do
        # Select heating patterns based on the zone
        if [ "$z" -eq 0 ]; then
            heating_patterns=("${heating_patterns_zone_0[@]}")
        else
            heating_patterns=("${heating_patterns_zone_9[@]}")
        fi

        for pattern in "${heating_patterns[@]}"
        do
            for temp in "${temperatures[@]}"
            do
                for case in "${cases[@]}"
                do
                    PARAMS+=("--exp_typ thermostat --zone $z --heating_pattern $pattern --algorithm rbc --case $case --rep $rep --wandb_name other_occupancies --wandb_tags other_occupancies --year 2023 --comfort_temp_setpoint $temp --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --inactivity_threshold 30 --holiday True")
                done
            done
        done
    done
done

# Run the job with singularity using the task ID as an index for PARAMS
singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
