#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 00:30:00
#SBATCH -J p-jjjl-SYNTHETIC
#SBATCH --array=0-4

source ~/.bashrc

# Define the `rep` values (only H28)
REPS=("H28")

# Define specific experiment setups for H28 with heating patterns thrice and once
PARAMS=(
    "--exp_typ thermostat --zone 0 --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name longer_heating_check_v3 --wandb_tags longer_heating_check_v3 --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    "--exp_typ thermostat --zone 9 --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name longer_heating_check_v3 --wandb_tags longer_heating_check_v3 --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    "--exp_typ thermostat --zone 9 --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name longer_heating_check_v3 --wandb_tags longer_heating_check_v3 --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    "--exp_typ thermostat --zone 9 --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name longer_heating_check_v3 --wandb_tags longer_heating_check_v3 --year 2023 --comfort_temp_setpoint 20.5 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    "--exp_typ thermostat --zone 9 --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name longer_heating_check_v3 --wandb_tags longer_heating_check_v3 --year 2023 --comfort_temp_setpoint 21 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern thrice --algorithm rbc --case 0 --rep H28 --wandb_name longer_heating_check_v3 --wandb_tags longer_heating_check_v3 --year 2023 --comfort_temp_setpoint 21 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern once --algorithm rbc --case 0 --rep H28 --wandb_name longer_heating_check_v3 --wandb_tags longer_heating_check_v3 --year 2023 --comfort_temp_setpoint 21 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name longer_heating_check_v3 --wandb_tags longer_heating_check_v3 --year 2023 --comfort_temp_setpoint 20.5 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name longer_heating_check_v2 --wandb_tags longer_heating_check_v2 --year 2023 --comfort_temp_setpoint 20.5 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name longer_heating_check_v2 --wandb_tags longer_heating_check_v2 --year 2023 --comfort_temp_setpoint 21 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name longer_heating_check_v2 --wandb_tags longer_heating_check_v2 --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name longer_heating_check_v2 --wandb_tags longer_heating_check_v2 --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern once --algorithm rbc --case 0 --rep H28 --wandb_name higher_setback_check --wandb_tags higher_setback_check --year 2023 --comfort_temp_setpoint 20.5 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name higher_setback_check --wandb_tags higher_setback_check --year 2023 --comfort_temp_setpoint 20.5 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern thrice --algorithm rbc --case 0 --rep H28 --wandb_name higher_setback_check --wandb_tags higher_setback_check --year 2023 --comfort_temp_setpoint 20.5 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern once --algorithm rbc --case 0 --rep H28 --wandb_name higher_setback_check --wandb_tags higher_setback_check --year 2023 --comfort_temp_setpoint 21 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern twice --algorithm rbc --case 0 --rep H28 --wandb_name higher_setback_check --wandb_tags higher_setback_check --year 2023 --comfort_temp_setpoint 21 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
    #"--exp_typ thermostat --zone 9 --heating_pattern thrice --algorithm rbc --case 0 --rep H28 --wandb_name higher_setback_check --wandb_tags higher_setback_check --year 2023 --comfort_temp_setpoint 21 --setback_temp_setpoint 16.5 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True"
)

# Run the job with singularity using the task ID as an index for PARAMS
singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
