#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 00:15:00
#SBATCH -J heating-exps
#SBATCH --array=0  # Job array range for all 54 combinations

source ~/.bashrc

# Define the PARAMS array dynamically:
PERIODS=("lynch" "beizaee")
CONTROLS=("conventional_control" "zonal_control" "occupancy_control")
PART_LOADS=("0_0" "0_2" "0_4")
EFFICIENCIES=("constant" "quadratic" "cubic")

# Generate all combinations of the parameters and add them to the PARAMS array
PARAMS=()

for PERIOD in "${PERIODS[@]}"; do
    for CONTROL in "${CONTROLS[@]}"; do
        for PART_LOAD in "${PART_LOADS[@]}"; do
            for EFFICIENCY in "${EFFICIENCIES[@]}"; do
                # Correctly pass the parameters with the correct flags
                PARAMS+=("--experiment $CONTROL --period $PERIOD --part_load $PART_LOAD --efficiency $EFFICIENCY")
            done
        done
    done
done

# Run the job with singularity using the task ID as an index for PARAMS
singularity run cubes-cluster.simg python3.9 run_exps.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}

# Check if the command was successful
STATUS=$?
if [ $STATUS -ne 0 ]; then
  echo "❌ Error in: $CONTROL $PERIOD $PART_LOAD $EFFICIENCY"
fi
