#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 00:04:00
#SBATCH -J heating-exp-quick

source ~/.bashrc

PERIOD="beizaee"
MODE="validation"
PART_LOAD="0_2"
EFFICIENCY="quadratic"
CONTROLS=("conventional_control" "zonal_control" "occupancy_control")

for CONTROL in "${CONTROLS[@]}"; do
  echo "▶ $CONTROL | period=$PERIOD | part=$PART_LOAD | eff=$EFFICIENCY | mode=$MODE"
  singularity run cubes-cluster.simg python3.9 run_exps.py \
    --experiment "$CONTROL" \
    --period "$PERIOD" \
    --part_load "$PART_LOAD" \
    --efficiency "$EFFICIENCY" \
    --mode "$MODE"
done
