#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 00:30:00
#SBATCH -J p-jjjl-case-sweep
#SBATCH --array=0-1

source ~/.bashrc

# Build parameter list
PARAMS=()
zones=(0 9)

for z in "${zones[@]}"
do
    case=0
    PARAMS+=("--exp_typ thermostat \
    --zone $z \
    --heating_pattern twice \
    --algorithm rbc \
    --case $case \
    --rep H28 \
    --wandb_name model_validation \
    --wandb_tags model_validation \
    --year 2023 \
    --comfort_temp_setpoint 20 \
    --setback_temp_setpoint 16 \
    --wandb_entity jjjl4 \
    --wandb_project jack-observations \
    --run_id True \
    --timesteps_per_hour 60 \
    --holiday True \
    --short_episode False \
    --inactivity_threshold 15 \
    --wandb_logging True \
    --no_ventilation True")
done


# Run the job with singularity using the task ID as an index for PARAMS
singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
