#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 01:00:00
#SBATCH -J p-jjjl-h28
#SBATCH --array=0-9

source ~/.bashrc


PARAMS=(
    "--exp_type supplementary_h28 --zone 0 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name SI_H28_Test_Run --wandb_tags rbc SI H28 Man Minute --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --pattern occupancy"
    "--exp_type supplementary_h28 --zone 9 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name SI_H28_Test_Run --wandb_tags rbc SI H28 Occ Minute --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --pattern occupancy"
    "--exp_type supplementary_h28 --zone 9 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name SI_H28_Test_Run --wandb_tags rbc SI H28 Occ Minute --year 2023 --comfort_temp_setpoint 20.5 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --pattern occupancy"
    "--exp_type supplementary_h28 --zone 9 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name SI_H28_Test_Run --wandb_tags rbc SI H28 Heat Minute --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --pattern heating"
    "--exp_type supplementary_h28 --zone 9 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name SI_H28_Test_Run --wandb_tags rbc SI H28 Heat Minute --year 2023 --comfort_temp_setpoint 20.5 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --pattern heating"
    "--exp_type supplementary_h28 --zone 0 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name SI_H28_Test_Run --wandb_tags rbc SI H28 Man --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 6 --pattern occupancy"
    "--exp_type supplementary_h28 --zone 9 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name SI_H28_Test_Run --wandb_tags rbc SI H28 Occ --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 6 --pattern occupancy"
    "--exp_type supplementary_h28 --zone 9 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name SI_H28_Test_Run --wandb_tags rbc SI H28 Occ  --year 2023 --comfort_temp_setpoint 20.5 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 6 --pattern occupancy"
    "--exp_type supplementary_h28 --zone 9 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name SI_H28_Test_Run --wandb_tags rbc SI H28 Heat --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 6 --pattern heating"
    "--exp_type supplementary_h28 --zone 9 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name SI_H28_Test_Run --wandb_tags rbc SI H28 Heat --year 2023 --comfort_temp_setpoint 20.5 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 6 --pattern heating"
    )



singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}