#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 2:00:00
#SBATCH -J p-jjjl-zoning
#SBATCH --array=0-10

source ~/.bashrc

PARAMS=(
"--exp_type thermostat --algorithm rbc --rbc_switch 2 --case 0 --rep 1 --iter 0 --wandb_name single_zone_control_manual --wandb_tags rbc zoning paper2 --year 2022 --comfort_temp_setpoint 20 --setback_temp_setpoint 15 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"
"--exp_type thermostat --algorithm rbc --rbc_switch 2 --case 0 --rep 1 --iter 1 --wandb_name single_zone_control_manual --wandb_tags rbc zoning paper2 --year 2022 --comfort_temp_setpoint 20 --setback_temp_setpoint 15 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"
"--exp_type thermostat --algorithm rbc --rbc_switch 2 --case 0 --rep 1 --iter 2 --wandb_name single_zone_control_manual --wandb_tags rbc zoning paper2 --year 2022 --comfort_temp_setpoint 20 --setback_temp_setpoint 15 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"
"--exp_type thermostat --algorithm rbc --rbc_switch 2 --case 0 --rep 1 --iter 3 --wandb_name single_zone_control_manual --wandb_tags rbc zoning paper2 --year 2022 --comfort_temp_setpoint 20 --setback_temp_setpoint 15 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"
"--exp_type thermostat --algorithm rbc --rbc_switch 2 --case 0 --rep 1 --iter 4 --wandb_name single_zone_control_manual --wandb_tags rbc zoning paper2 --year 2022 --comfort_temp_setpoint 20 --setback_temp_setpoint 15 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"
"--exp_type thermostat --algorithm rbc --rbc_switch 2 --case 0 --rep 1 --iter 5 --wandb_name single_zone_control_manual --wandb_tags rbc zoning paper2 --year 2022 --comfort_temp_setpoint 20 --setback_temp_setpoint 15 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"
"--exp_type thermostat --algorithm rbc --rbc_switch 2 --case 0 --rep 1 --iter 6 --wandb_name single_zone_control_manual --wandb_tags rbc zoning paper2 --year 2022 --comfort_temp_setpoint 20 --setback_temp_setpoint 15 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"
"--exp_type thermostat --algorithm rbc --rbc_switch 2 --case 0 --rep 1 --iter 7 --wandb_name single_zone_control_manual --wandb_tags rbc zoning paper2 --year 2022 --comfort_temp_setpoint 20 --setback_temp_setpoint 15 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"
"--exp_type thermostat --algorithm rbc --rbc_switch 2 --case 0 --rep 1 --iter 8 --wandb_name single_zone_control_manual --wandb_tags rbc zoning paper2 --year 2022 --comfort_temp_setpoint 20 --setback_temp_setpoint 15 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"
"--exp_type thermostat --algorithm rbc --rbc_switch 2 --case 0 --rep 1 --iter 9 --wandb_name single_zone_control_manual --wandb_tags rbc zoning paper2 --year 2022 --comfort_temp_setpoint 20 --setback_temp_setpoint 15 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"
"--exp_type thermostat --algorithm rbc --rbc_switch 2 --case 0 --rep 1 --wandb_name single_zone_control_manual_baseline --wandb_tags rbc zoning paper2 --year 2022 --comfort_temp_setpoint 20 --setback_temp_setpoint 15 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"
)

singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
