#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 01:00:00
#SBATCH -J p-jjjl-final-v4
#SBATCH --array=0-99

source ~/.bashrc

# Define the PARAMS array dynamically:
# Zone 0: 3 heating patterns, 5 temperatures, 5 reps -> 3 * 5 * 5 = 75 jobs
# Zone 9: 1 heating pattern, 5 temperatures, 5 reps -> 1 * 5 * 5 = 25 jobs
PARAMS=()
for z in 0 9
do
    if [ "$z" -eq 0 ]; then
        heating_patterns=("once" "twice" "thrice")  # Three heating patterns for zone 0
    else
        heating_patterns=("twice")  # Single heating pattern for zone 9
    fi

    for pattern in "${heating_patterns[@]}"
    do
        for temp in {18..22}  # Comfort temperatures from 18 to 22 (5 values)
        do
            for rep in {0..4}  # Repetitions from 0 to 4 (5 reps)
            do
                PARAMS+=("--exp_typ thermostat --zone $z --heating_pattern $pattern --algorithm rbc --rbc_switch 2 --case 0 --rep $rep --wandb_name thernostat_test_run --wandb_tags thermostat test --year 2023 --comfort_temp_setpoint $temp --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60")
            done
        done
    done
done

# Run the job with singularity using the task ID as an index for PARAMS
singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
