#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 1:00:00
#SBATCH -J p-jjjl-thermostat-final
#SBATCH --array=0-54

source ~/.bashrc

YEARS=("2022" "2023")
CASES=(14)
REPS=(0) #1 2 3 4)
TEMP_SEEDS=(42 30 15)
ON_OFF_SEEDS=(5 15 10)
ZONES=(0 4 9)

# Function to generate parameters based on the input values
generate_params() {
    local year=$1
    local case=$2
    local rep=$3
    local temp_seed=$4
    local on_off_seed=$5
    local zone=$6
    local wandb_name="paper2_final_runs_v1"

    echo "--exp_type thermostat --zone $zone --heating_set_temp_seed $temp_seed --heating_on_off_seed $on_off_seed --algorithm rbc --rbc_switch 2 --case $case --rep $rep --wandb_name $wandb_name --wandb_tags rbc final paper2 --year $year --comfort_temp_setpoint 20 --setback_temp_setpoint 15 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True"
}

# Calculate total number of combinations
num_years=${#YEARS[@]}
num_cases=${#CASES[@]}
num_reps=${#REPS[@]}
num_temp_seeds=${#TEMP_SEEDS[@]}
num_on_off_seeds=${#ON_OFF_SEEDS[@]}
num_zones=${#ZONES[@]}
total_combinations=$((num_years * num_cases * num_reps * num_temp_seeds * num_on_off_seeds * num_zones))

# Determine the indices based on the SLURM_ARRAY_TASK_ID
index=$SLURM_ARRAY_TASK_ID

year_index=$((index % num_years))
case_index=$(((index / num_years) % num_cases))
rep_index=$(((index / (num_years * num_cases)) % num_reps))
temp_seed_index=$(((index / (num_years * num_cases * num_reps)) % num_temp_seeds))
on_off_seed_index=$(((index / (num_years * num_cases * num_reps * num_temp_seeds)) % num_on_off_seeds))
zone_index=$(((index / (num_years * num_cases * num_reps * num_temp_seeds * num_on_off_seeds)) % num_zones))

year=${YEARS[$year_index]}
case=${CASES[$case_index]}
rep=${REPS[$rep_index]}
temp_seed=${TEMP_SEEDS[$temp_seed_index]}
on_off_seed=${ON_OFF_SEEDS[$on_off_seed_index]}
zone=${ZONES[$zone_index]}

PARAMS=$(generate_params $year $case $rep $temp_seed $on_off_seed $zone)

singularity run cubes-cluster.simg python3.9 main_jack.py $PARAMS
