#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=3420
#SBATCH -N 1
#SBATCH -t 12:00:00
#SBATCH -J p-jjjl-obs
#SBATCH --array=0-1

source ~/.bashrc

PARAMS=(
"--wandb_tags parsons rbc  --case 0 --year 2022 --rep 0 --emissions_weight 1 --algorithm rbc --rbc_switch 0 --wandb_entity jjjl4 --wandb_project jack-observations --comfort_temp_setpoint 20 --setback_temp_setpoint 12 --reward_function_type Linear --timesteps_per_hour 6 --occupancy_schedule stochastic_occupancy --sleep_hours True --map_setpoints_to_comfort_space False"
"--wandb_tags parsons sac  --case 0 --year 2022 --rep 0 --emissions_weight 1 --algorithm sac --wandb_entity jjjl4 --wandb_project jack-observations --comfort_temp_setpoint 20 --setback_temp_setpoint 12 --discount 0.999 --batch_size 32  --critic_hidden_layers 8 --critic_hidden_dimension 128 --actor_hidden_layers 8 --actor_hidden_dimension 128  --map_setpoints_to_comfort_space True  --occupancy_schedule stochastic_occupancy --sleep_hours True --forecast_length 0  --normalise_observations True  --n_frame_stack 4 --discrete_actions True --temperature_weight 1 --init_temperature 0.0 --learnable_temperature False  --incremental_actions True"
 )

singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
