#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 01:00:00
#SBATCH -J p-jjjl-h28
#SBATCH --array=0-1

source ~/.bashrc


PARAMS=(
    "--exp_type thermostat --zone 90 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name beizaee_validation --wandb_tags rbc SI beizaee timed --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --pattern occupancy"
    "--exp_type thermostat --zone 99 --heating_set_temp_seed 42 --heating_on_off_seed 10 --algorithm rbc --rbc_switch 2 --case 0 --rep 0 --wandb_name beizaee_validation --wandb_tags rbc SI beizaee zonal --year 2023 --comfort_temp_setpoint 20 --setback_temp_setpoint 16 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --pattern occupancy"
     )



singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}