#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 00:30:00
#SBATCH -J p-jjjl-SYNTHETIC
#SBATCH --array=0-14 # Total jobs (2 zones * 15 cases)

source ~/.bashrc

# Define the `rep` values, `zones`, and `cases`
REPS=("H28")
ZONES=(9)
CASES=({0..14})  # Cases from 0 to 14

# Set constant comfort and setback temperatures
comfort_temp=20.5
setback_temp=16

# Create the PARAMS array dynamically by looping over `cases`, `zones`, and `rep`
PARAMS=()
for rep in "${REPS[@]}"; do
    for case in "${CASES[@]}"; do
        for zone in "${ZONES[@]}"; do
            PARAMS+=("--exp_typ thermostat --zone $zone --heating_pattern twice --algorithm rbc --case $case --rep $rep --wandb_name sleep_test --wandb_tags sleep_test --year 2023 --comfort_temp_setpoint $comfort_temp --setback_temp_setpoint $setback_temp --wandb_entity jjjl4 --wandb_project jack-observations --run_id True --timesteps_per_hour 60 --holiday True")
        done
    done
done

# Run the job with singularity using the task ID as an index for PARAMS
singularity run cubes-cluster.simg python3.9 main_jack.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
