#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake-himem
#SBATCH --mem=3420
#SBATCH -N 1
#SBATCH -t 12:00:00
#SBATCH -J leiden-job
#SBATCH --array=0-1

source ~/.bashrc

PARAMS=(
 "--wandb_tags foresight --case 10 --year 2022 --rep 0 --emissions_weight 1 --algorithm sac --wandb_entity hannesg --wandb_project Leiden-paper --comfort_temp_setpoint 20 --setback_temp_setpoint 17 --discount 0.99 --batch_size 64 --critic_learning_rate 0.0001 --actor_learning_rate 0.0001 --alpha_learning_rate 0.0001 --critic_hidden_layers 2 --critic_hidden_dimension 512 --actor_hidden_layers 2 --actor_hidden_dimension 512 --reward_function_type Linear"
 "--wandb_tags foresight --case 10 --year 2022 --rep 0 --emissions_weight 1 --algorithm sac --wandb_entity hannesg --wandb_project Leiden-paper --comfort_temp_setpoint 20 --setback_temp_setpoint 17 --discount 0.99 --batch_size 64 --critic_learning_rate 0.0001 --actor_learning_rate 0.0001 --alpha_learning_rate 0.0001 --critic_hidden_layers 2 --critic_hidden_dimension 512 --actor_hidden_layers 2 --actor_hidden_dimension 512 --reward_function_type Linear --force_comfort False"
 )

singularity run cubes-cluster.simg python3.9 main_leiden.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
