#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake-himem
#SBATCH --mem=3420
#SBATCH -N 1
#SBATCH -t 10:00:00
#SBATCH -J leiden-job-case-12-fixed-occupancy-setpoints-false
#SBATCH --array=0-3

source ~/.bashrc

PARAMS=(
"--case 12 --year 2022 --rep 0 --emissions_weight 20 --map_setpoints_to_comfort_space=False --algorithm sac --wandb_entity hannesg --wandb_project Leiden-paper --discount 0.99 --occupancy_schedule=fixed --wandb_tags comfort_setpoints_false"
#"--case 10 --year 2022 --rep 0 --emissions_weight 20 --map_setpoints_to_comfort_space=False --algorithm sac --wandb_entity hannesg --wandb_project Leiden-paper --discount 0.99 --occupancy_schedule=deterministic --wandb_tags comfort_setpoints_false"
"--case 12 --year 2022 --rep 0 --emissions_weight 20 --map_setpoints_to_comfort_space=False --algorithm rbc --rbc_switch=0 --wandb_entity hannesg --wandb_project Leiden-paper --discount 0.99 --occupancy_schedule=fixed"
"--case 12 --year 2022 --rep 0 --emissions_weight 20 --map_setpoints_to_comfort_space=False --algorithm rbc --rbc_switch=1 --wandb_entity hannesg --wandb_project Leiden-paper --discount 0.99 --occupancy_schedule=fixed"
"--case 12 --year 2022 --rep 0 --emissions_weight 20 --map_setpoints_to_comfort_space=False --algorithm rbc --rbc_switch=2 --wandb_entity hannesg --wandb_project Leiden-paper --discount 0.99 --occupancy_schedule=fixed"
 )

singularity run cubes-cluster.simg python3.9 main_leiden.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}
