#!/bin/bash
#SBATCH -A CULLEN-SL3-CPU
#SBATCH -p icelake-himem
#SBATCH --mem=10000
#SBATCH -N 1
#SBATCH -t 12:00:00
#SBATCH -J leiden-job
#SBATCH --array=0

source ~/.bashrc

PARAMS=(
 "--case=0 --year=2017 --rep=0 --temperature_weight=1 --emissions_weight=1 --air_quality_weight=1 --load_agent=False"
# "--case=0 --year=2017 --rep=0 --temperature_weight=1 --emissions_weight=5 --air_quality_weight=1 --load_agent=False"
# "--case=0 --year=2017 --rep=0 --temperature_weight=1 --emissions_weight=10 --air_quality_weight=1 --load_agent=False"
# "--case=0 --year=2017 --rep=0 --temperature_weight=1 --emissions_weight=15 --air_quality_weight=1 --load_agent=False"
# "--case=0 --year=2017 --rep=0 --temperature_weight=1 --emissions_weight=20 --air_quality_weight=1 --load_agent=False"
# "--case=0 --year=2017 --rep=0 --temperature_weight=1 --emissions_weight=25 --air_quality_weight=1 --load_agent=False"
)

singularity run cubes-cluster.simg python3.9 main_leiden.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}