#!/bin/bash
#SBATCH -A CULLEN-SL3-CPU
#SBATCH -p icelake-himem
#SBATCH --mem=10000
#SBATCH -N 1
#SBATCH -t 12:00:00
#SBATCH -J sysiphus-case-12-sac-charge-discharge-low-alpha
#SBATCH --array=0-7

source ~/.bashrc

PARAMS=(
 "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --discount=0.999 --alpha_learning_rate=0.00005 --init_temperature=0.5 --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only charge-discharge"
 "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --discount=0.999 --alpha_learning_rate=0.000005 --init_temperature=0.5 --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only charge-discharge"
 "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --discount=0.999 --alpha_learning_rate=0.00005 --init_temperature=1 --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only charge-discharge"
 "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --discount=0.999 --alpha_learning_rate=0.000005 --init_temperature=1 --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only charge-discharge"
 "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --discount=0.99 --alpha_learning_rate=0.00005 --init_temperature=0.5 --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only charge-discharge"
 "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --discount=0.99 --alpha_learning_rate=0.000005 --init_temperature=0.5 --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only charge-discharge"
 "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --discount=0.99 --alpha_learning_rate=0.00005 --init_temperature=1 --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only charge-discharge"
 "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --discount=0.99 --alpha_learning_rate=0.000005 --init_temperature=1 --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only charge-discharge"
# "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --wandb_run_id=qzb1vdpq --wandb_model_id=17280.pickle --load_agent=True --discount=0.999 --init_temperature=0.1  --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only fixed_sac_temperature"
# "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --wandb_run_id=d89xnxt9 --wandb_model_id=17280.pickle --load_agent=True --discount=0.999 --init_temperature=0.5  --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only fixed_sac_temperature"
# "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --wandb_run_id=fpv2b7v3 --wandb_model_id=23760.pickle --load_agent=True --discount=0.999 --init_temperature=1  --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only fixed_sac_temperature"
# "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --wandb_run_id=o4ppnyid --wandb_model_id=17280.pickle --load_agent=True --discount=0.999 --init_temperature=5  --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only fixed_sac_temperature"
)

singularity run cubes-cluster.simg python3.9 main_leiden.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}