#!/bin/bash
#SBATCH -A CULLEN-SL3-CPU
#SBATCH -p icelake-himem
#SBATCH --mem=10000
#SBATCH -N 1
#SBATCH -t 12:00:00
#SBATCH -J sysiphus-case-12-sac-fixed-temp
#SBATCH --array=0-3

source ~/.bashrc

PARAMS=(
# "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --wandb_project cubes --temperature_margin=2.5 --emissions_weight=1 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --wandb_tags sac temp_and_emissions centred_20"
# "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --wandb_project cubes --temperature_margin=2.5 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --wandb_tags sac temp_and_emissions centred_20"
# "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --wandb_project cubes --temperature_margin=2.5 --emissions_weight=5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --wandb_tags sac temp_and_emissions centred_20"
# "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --wandb_project cubes --temperature_margin=2.5 --emissions_weight=10 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --wandb_tags sac temp_and_emissions centred_20"
 "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --init_temperature=0.1 --learnable_temperature=False --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only fixed_sac_temperature"
 "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --init_temperature=0.25 --learnable_temperature=False --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only fixed_sac_temperature"
 "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --init_temperature=0.5 --learnable_temperature=False --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only fixed_sac_temperature"
 "--case 12 --year 2022 --rep 0 --short_episode=True --algorithm sac  --wandb_entity enjeeneer --init_temperature=1 --learnable_temperature=False --wandb_project cubes --temperature_margin=1 --emissions_weight=2.5 --map_setpoints_to_comfort_space=False --occupancy_schedule=always_occupied --battery_only=True --wandb_tags sac battery_only fixed_sac_temperature"
)

singularity run cubes-cluster.simg python3.9 main_leiden.py ${PARAMS[$SLURM_ARRAY_TASK_ID]}