#!/bin/bash
#SBATCH -A CABRERA-SERRENHO-SL3-CPU
#SBATCH -p icelake
#SBATCH --mem=6840
#SBATCH -N 1
#SBATCH -t 00:15:00
#SBATCH -J p-jjjl-testing
#SBATCH --array=0-1

singularity run cubes-cluster.simg python3.9 main_jack.py --exp_type thermostat --zone 9 --heating_set_temp_seed 42 --heating_on_off_seed 5 --algorithm rbc --rbc_switch 2 --case 11 --rep 0 --wandb_name paper2_test_monitor --wandb_tags rbc final paper2 --year 2022 --comfort_temp_setpoint 18 --setback_temp_setpoint 13 --wandb_entity jjjl4 --wandb_project jack-observations --run_id True