"""Holds config data for databases."""

from pathlib import Path
from cubes.constants import package_directory

# --- data paths ---
BASE_PATH = Path(package_directory)
GEOMETRY_PATH = BASE_PATH / Path("data/housing_stock/ambience-geometry-eu.xlsx")
SYSTEMS_PATH = BASE_PATH / Path("data/housing_stock/ambience-systems-eu.xlsx")

# --- database features ---
ID_COLUMN = "REFERENCE BUILDING CODE"
GEOMETRY_FEATURES = [
    "REFERENCE BUILDING CODE",
    "REFERENCE BUILDING COUNTRY CODE",
    "REFERENCE BUILDING USE CODE",
    "REFERENCE BUILDING CONSTRUCTION YEAR LOW",
    "REFERENCE BUILDING CONSTRUCTION YEAR HIGH",
    "REFERENCE BUILDING MATERIAL COMBINATION CODE",
    "REFERENCE BUILDING USEFUL FLOOR AREA (m2)",
    "NUMBER OF REFERENCE BUILDINGS IN THE BUILDING STOCK SEGMENT",
    "NUMBER OF REFERENCE BUILDING STOREYS",
    "REFERENCE BUILDING GROUND FLOOR AREA (m2)",
    "REFERENCE BUILDING WALL AREA (m2)",
    "REFERENCE BUILDING WINDOW AREA (m2)",
    "REFERENCE BUILDING ROOF AREA (m2)",
    "REFERENCE BUILDING FLOOR MATERIAL",
    "REFERENCE BUILDING FLOOR MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING FLOOR MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "REFERENCE BUILDING FLOOR MATERIAL DENSITY (kg/m3)",
    "REFERENCE BUILDING FLOOR MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "REFERENCE BUILDING FLOOR INSULATION MATERIAL",
    "REFERENCE BUILDING FLOOR INSULATION MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING FLOOR INSULATION MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "REFERENCE BUILDING FLOOR INSULATION MATERIAL DENSITY (kg/m3)",
    "REFERENCE BUILDING FLOOR INSULATION MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "REFERENCE BUILDING FLOOR U-VALUE (W/m2/K)",
    "REFERENCE BUILDING WALL MATERIAL",
    "REFERENCE BUILDING WALL MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING WALL MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "REFERENCE BUILDING WALL MATERIAL DENSITY (kg/m3)",
    "REFERENCE BUILDING WALL MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "REFERENCE BUILDING WALL INSULATION MATERIAL",
    "REFERENCE BUILDING WALL INSULATION MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING WALL INSULATION MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "REFERENCE BUILDING WALL INSULATION MATERIAL DENSITY (kg/m3)",
    "REFERENCE BUILDING WALL INSULATION MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "REFERENCE BUILDING WALL U-VALUE (W/m2/K)",
    "REFERENCE BUILDING WINDOW TYPE",
    "REFERENCE BUILDING WINDOW GLAZING TYPE",
    "REFERENCE BUILDING FRAME MATERIAL",
    "REFERENCE BUILDING WINDOW COATED",
    "REFERENCE BUILDING WINDOW FILLING GAS",
    "REFERENCE BUILDING WINDOW U-VALUE (W/m2/K)",
    "REFERENCE BUILDING ROOF MATERIAL",
    "REFERENCE BUILDING ROOF MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING ROOF MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "REFERENCE BUILDING ROOF MATERIAL DENSITY (kg/m3)",
    "REFERENCE BUILDING ROOF MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "REFERENCE BUILDING ROOF INSULATION MATERIAL",
    "REFERENCE BUILDING ROOF INSULATION MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING ROOF INSULATION MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "REFERENCE BUILDING ROOF INSULATION MATERIAL DENSITY (kg/m3)",
    "REFERENCE BUILDING ROOF INSULATION MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "REFERENCE BUILDING ROOF U-VALUE (W/m2/K)",
    "BUILDING STOCK SEGMENT USEFUL FLOOR AREA (m2)",
    "BUILDING STOCK SEGMENT NUMBER OF BUILDINGS",
]

GEOMETRY_MERGE_FEATURES = [
    "REFERENCE BUILDING CODE",
]
