"""Holds config data for databases."""

from pathlib import Path
from cubes.constants import package_directory

# --- data paths ---
BASE_PATH = Path(package_directory)
CLEANED_BUILDING_DATASET_PATH = BASE_PATH / Path("building-data.csv")
CLEANED_MATERIAL_DATASET_PATH = BASE_PATH / Path("materials.pickle")
CLEANED_WINDOWS_DATASET_PATH = BASE_PATH / Path("windows.pickle")
LOCATION_PATH = BASE_PATH / Path("data/location/eu-spatial-dwelling-distribution.xlsx")
GEOMETRY_PATH = BASE_PATH / Path("data/housing_stock/geometry.xlsx")
HVAC_PATH = BASE_PATH / Path("data/energy_systems/hvac.xlsx")
HVAC_SCHEMA_PATH = BASE_PATH / Path("data/energy_systems/hvac-schema.xlsx")
AIR_INFILTRATION_PATH = BASE_PATH / Path("data/housing_stock/air-infiltration.xlsx")
MATERIALS_PATH = BASE_PATH / Path("data/materials/materials.xlsx")
WINDOWS_PATH = BASE_PATH / Path("data/materials/windows.xlsx")
WEATHER_PATH = BASE_PATH / Path("data/weather/weather.xlsx")
SOLAR_PV_PATH = BASE_PATH / Path("data/energy_systems/solar-pv.xlsx")
BATTERIES_PATH = BASE_PATH / Path("data/energy_systems/batteries.xlsx")
FRIDGE_FREEZER_PATH = BASE_PATH / Path("data/energy_systems/fridge-freezers.xlsx")
ELECTRIC_VEHICLE_PATH = BASE_PATH / Path("data/energy_systems/electric-vehicles.xlsx")
GRID_CARBON_PATH = BASE_PATH / Path("data/grid/carbon-intensity.xlsx")
EMISSION_FACTORS_PATH = BASE_PATH / Path("data/grid/emission-factors.xlsx")

# --- misc ---
RESIDENTIAL_BUILDING_CODES = ["ABL", "MFH", "SFH", "TH"]

COUNTRIES = [
    "AT",
    "BE",
    "BG",
    "CZ",
    "DE",
    "DK",
    "EE",
    "EL",
    "ES",
    "FI",
    "FR",
    "HR",
    "HU",
    "IE",
    "IT",
    "LT",
    "LU",
    "LV",
    "MT",
    "NL",
    "PL",
    "PT",
    "RO",
    "SE",
    "SI",
    "SK",
    "GB",
]

# for entsoe api
TIMEZONES = {
    "AT": "Europe/Vienna",
    "BE": "Europe/Brussels",
    "BG": "Europe/Sofia",
    "CZ": "Europe/Prague",
    "DE": "Europe/Berlin",
    "DK": "Europe/Copenhagen",
    "EE": "Europe/Tallinn",
    "EL": "Europe/Athens",
    "ES": "Europe/Madrid",
    "FI": "Europe/Helsinki",
    "FR": "Europe/Paris",
    "HR": "Europe/Zagreb",
    "HU": "Europe/Budapest",
    "IE": "Europe/Dublin",
    "IT": "Europe/Rome",
    "LT": "Europe/Vilnius",
    "LU": "Europe/Luxembourg",
    "LV": "Europe/Riga",
    "MT": "Europe/Malta",
    "NL": "Europe/Amsterdam",
    "PL": "Europe/Warsaw",
    "PT": "Europe/Lisbon",
    "RO": "Europe/Bucharest",
    "SE": "Europe/Stockholm",
    "SI": "Europe/Ljubljana",
    "SK": "Europe/Bratislava",
    "GB": "Europe/London",
}

YEARS = [
    "2022",
    "2021",
    "2020",
    "2019",
    "2018",
    "2017",
]

OIKOLAB_API_KEY = "6f8a9cf2311245a783c97c7275de97b2"
ENTSOE_API_KEY = "47715a4d-d130-4de5-ae82-2db13b61c392"

# --- database features ---
COMMON_FEATURES = [
    "REFERENCE BUILDING USE CODE"
]  # common features for all databases that we use for merging

REGION_ID_COLUMN = "NUTS 3 REGION"
BUILDING_ID_COLUMN = "REFERENCE BUILDING CODE"
GEOMETRY_FEATURES = [
    "REFERENCE BUILDING CODE",
    "REFERENCE BUILDING COUNTRY CODE",
    "REFERENCE BUILDING USE CODE",
    "REFERENCE BUILDING CONSTRUCTION YEAR LOW",
    "REFERENCE BUILDING CONSTRUCTION YEAR HIGH",
    "REFERENCE BUILDING MATERIAL COMBINATION CODE",
    "REFERENCE BUILDING USEFUL FLOOR AREA (m2)",
    "NUMBER OF REFERENCE BUILDINGS IN THE BUILDING STOCK SEGMENT",
    "REFERENCE BUILDING NUMBER OF STOREYS",
    "REFERENCE BUILDING FLOOR TO FLOOR HEIGHT",
    "REFERENCE BUILDING GROUND FLOOR AREA (m2)",
    "REFERENCE BUILDING WALL AREA (m2)",
    "REFERENCE BUILDING WINDOW AREA (m2)",
    "REFERENCE BUILDING ROOF AREA (m2)",
    "REFERENCE BUILDING FLOOR MATERIAL",
    "REFERENCE BUILDING FLOOR MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING FLOOR MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "REFERENCE BUILDING FLOOR MATERIAL DENSITY (kg/m3)",
    "REFERENCE BUILDING FLOOR MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "REFERENCE BUILDING FLOOR INSULATION MATERIAL",
    "REFERENCE BUILDING FLOOR INSULATION MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING FLOOR INSULATION MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "REFERENCE BUILDING FLOOR INSULATION MATERIAL DENSITY (kg/m3)",
    "REFERENCE BUILDING FLOOR INSULATION MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "REFERENCE BUILDING FLOOR U-VALUE (W/m2/K)",
    "REFERENCE BUILDING WALL MATERIAL",
    "REFERENCE BUILDING WALL MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING WALL MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "REFERENCE BUILDING WALL MATERIAL DENSITY (kg/m3)",
    "REFERENCE BUILDING WALL MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "REFERENCE BUILDING WALL INSULATION MATERIAL",
    "REFERENCE BUILDING WALL INSULATION MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING WALL INSULATION MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "REFERENCE BUILDING WALL INSULATION MATERIAL DENSITY (kg/m3)",
    "REFERENCE BUILDING WALL INSULATION MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "REFERENCE BUILDING WALL U-VALUE (W/m2/K)",
    "REFERENCE BUILDING WINDOW TYPE",
    "REFERENCE BUILDING WINDOW GLAZING TYPE",
    "REFERENCE BUILDING FRAME MATERIAL",
    "REFERENCE BUILDING WINDOW COATED",
    "REFERENCE BUILDING WINDOW FILLING GAS",
    "REFERENCE BUILDING WINDOW U-VALUE (W/m2/K)",
    "REFERENCE BUILDING ROOF MATERIAL",
    "REFERENCE BUILDING ROOF MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING ROOF MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "REFERENCE BUILDING ROOF MATERIAL DENSITY (kg/m3)",
    "REFERENCE BUILDING ROOF MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "REFERENCE BUILDING ROOF INSULATION MATERIAL",
    "REFERENCE BUILDING ROOF INSULATION MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING ROOF INSULATION MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "REFERENCE BUILDING ROOF INSULATION MATERIAL DENSITY (kg/m3)",
    "REFERENCE BUILDING ROOF INSULATION MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "REFERENCE BUILDING ROOF U-VALUE (W/m2/K)",
    "BUILDING STOCK SEGMENT USEFUL FLOOR AREA (m2)",
    "BUILDING STOCK SEGMENT NUMBER OF BUILDINGS",
    "ENERGYPLUS ZONING",
    "REFERENCE BUILDING UPPER FLOOR MATERIAL",
    "REFERENCE BUILDING UPPER FLOOR MATERIAL THICKNESS (m)",
    "REFERENCE BUILDING STOREY HEIGHT (m)",
]

HVAC_FEATURES = [
    "REFERENCE BUILDING CODE",
    "REFERENCE BUILDING COUNTRY CODE",
    "HEATING SYSTEM 1 TECHNOLOGY",
    "HEATING SYSTEM 1 DIMENSIONS",
    "HEATING SYSTEM 1 FUEL USED",
    "HEATING SYSTEM 1 EFFICIENCY",
    "HEATING SYSTEM 1 PREVALENCY ON BUILDING STOCK",
    "HEATING SYSTEM 2 TECHNOLOGY",
    "HEATING SYSTEM 2 DIMENSIONS",
    "HEATING SYSTEM 2 FUEL USED",
    "HEATING SYSTEM 2 EFFICIENCY",
    "HEATING SYSTEM 2 PREVALENCY ON BUILDING STOCK",
    "HEATING SYSTEM 3 TECHNOLOGY",
    "HEATING SYSTEM 3 DIMENSIONS",
    "HEATING SYSTEM 3 FUEL USED",
    "HEATING SYSTEM 3 EFFICIENCY",
    "HEATING SYSTEM 3 PREVALENCY ON BUILDING STOCK",
    "DHW SYSTEM 1 TECHNOLOGY",
    "DHW SYSTEM 1 DIMENSIONS",
    "DHW SYSTEM 1 FUEL USED",
    "DHW SYSTEM 1 EFFICIENCY",
    "DHW SYSTEM 1 PREVALENCY ON BUILDING STOCK",
    "DHW SYSTEM 2 TECHNOLOGY",
    "DHW SYSTEM 2 DIMENSIONS",
    "DHW SYSTEM 2 FUEL USED",
    "DHW SYSTEM 2 EFFICIENCY",
    "DHW SYSTEM 2 PREVALENCY ON BUILDING STOCK",
    "DHW SYSTEM 3 TECHNOLOGY",
    "DHW SYSTEM 3 DIMENSIONS",
    "DHW SYSTEM 3 FUEL USED",
    "DHW SYSTEM 3 EFFICIENCY",
    "DHW SYSTEM 3 PREVALENCY ON BUILDING STOCK",
    "COOLING SYSTEMS PRESENCE ON BUILDING STOCK",
]

AIR_INFILTRATION_FEATURES = [
    "REFERENCE BUILDING USE CODE",
    "MERGE INTEGER",
    "REFERENCE BUILDING CONSTRUCTION YEAR LOW",
    "REFERENCE BUILDING CONSTRUCTION YEAR HIGH",
    "AIR INFILTRATION",
]

MATERIALS_FEATURES = [
    "Material",
    "Thermal_Conductivity",
    "Thermal_Resistance",
    "Density",
    "Specific_Heat_Capacity",
    "Roughness",
    "Thermal_Absorptance",
    "Solar_Absorptance",
    "Visual_Absorptance",
    "NoMass",
    "AirGap",
]

WINDOWS_FEATURES = [
    "Name",
    "Optical Data Type",
    "Window Glass Spectral Data Set Name",
    "Thickness",
    "Solar Transmittance at Normal Incidence",
    "Front Side Solar Reflectance at Normal Incidence",
    "Back Side Solar Reflectance at Normal Incidence",
    "Visible Transmittance at Normal Incidence",
    "Front Side Visible Reflectance at Normal",
    "Back Side Visible Reflectance at Normal",
    "Infrared Transmittance at Normal Incidence",
    "Front Side Infrared Hemispherical Emissivity",
    "Back Side Infrared Hemispherical Emissivity",
    "Conductivity",
    "U Factor",
    "Solar Heat Gain Coefficient",
    "Simple Glazing",
]

LOCATION_FEATURES = [
    "NUTS 3 REGION",
    "COUNTRY CODE",
    "REGION DWELLINGS",
    "REGION OCCUPIED DWELLINGS",
    "REGION UNOCCUPIED DWELLINGS",
    "REGION POPULATION",
    "REGION MEAN OCCUPANTS PER BUILDING",
    "TERRAIN",
]

WEATHER_FEATURES = [
    "WEATHER FILE 2017",
    "WEATHER FILE 2018",
    "WEATHER FILE 2019",
    "WEATHER FILE 2020",
    "WEATHER FILE 2021",
    "WEATHER FILE 2022",
]

GRID_FEATURES = [
    "GRID CARBON FILE 2017",
    "GRID CARBON FILE 2018",
    "GRID CARBON FILE 2019",
    "GRID CARBON FILE 2020",
    "GRID CARBON FILE 2021",
    "GRID CARBON FILE 2022",
]

SOLAR_PV_FEATURES = [
    "COUNTRY CODE",
    "COUNTRY SOLAR PV INSTALLATIONS",
    "SOLAR PV TECHNICAL POTENTIAL INSTALLATIONS",
    "MEAN SOLAR PV PANEL EFFICIENCY",
    "MEAN SOLAR PV ACTIVE AREA FRACTION",
]

BATTERIES_FEATURES = [
    "REFERENCE BUILDING USE CODE",
    "SMALL BATTERY SIZE (KWH)",
    "MEDIUM BATTERY SIZE (KWH)",
    "LARGE BATTERY SIZE (KWH)",
    "SMALL BATTERY SIZE PROBABILITY",
    "MEDIUM BATTERY SIZE PROBABILITY",
    "LARGE BATTERY SIZE PROBABILITY",
]

FRIDGE_FREEZER_FEATURES = [
    "FRIDGE COMPRESSOR REFRIGERANT",
    "FRIDGE COMPRESSOR COEFFICIENT OF PERFORMANCE",
    "FRIDGE COMPRESSOR TYPE",
    "FRIDGE RACK RATED TOTAL COOLING CAPACITY",
    "FRIDGE RACK CASE LENGTH",
    "FRIDGE RACK CASE WIDTH",
    "FRIDGE RACK CASE HEIGHT",
    "FRIDGE RATED AMBIENT TEMPERATURE",
    "FRIDGE RATED AMBIENT RELATIVE HUMIDITY",
    "FRIDGE CASE DEFROST TYPE",
    "FRIDGE CASE OPERATING TEMPERATURE",
    "FREEZER COMPRESSOR REFRIGERANT",
    "FREEZER COMPRESSOR COEFFICIENT OF PERFORMANCE",
    "FREEZER COMPRESSOR TYPE",
    "FREEZER RACK RATED TOTAL COOLING CAPACITY",
    "FREEZER RACK CASE LENGTH",
    "FREEZER RACK CASE WIDTH",
    "FREEZER RACK CASE HEIGHT",
    "FREEZER RATED AMBIENT TEMPERATURE",
    "FREEZER RATED AMBIENT RELATIVE HUMIDITY",
    "FREEZER CASE DEFROST TYPE",
    "FREEZER CASE OPERATING TEMPERATURE",
]

ELECTRIC_VEHICLE_FEATURES = [
    "COUNTRY CODE",
    "COUNTRY PROBABILITY BEVS",
    "COUNTRY PROBABILITY PHEVS",
    "BEV MINIMUM BATTERY SIZE (kWh)",
    "BEV MAXIMUM BATTERY SIZE (kWh)",
    "PHEV MINIMUM BATTERY SIZE (kWh)",
    "PHEV MAXIMUM BATTERY SIZE (kWh)",
]

# transforms region names that are not recognized by OpenStreetMap
WEATHER_NUTS_3_TRANSFORMATIONS = {
    "Bezirk Verviers - Deutschsprachige Gemeinschaft": "Bezirk Verviers",
    "Border (NUTS 2013)": "Ballyconnell",
    "Midland (NUTS 2013)": "Tallamore Ireland",
    "West (NUTS 2013)": "Westport Ireland",
    "Dublin (NUTS 2013)": "Dublin",
    "Mid-East (NUTS 2013)": "Naas Ireland",
    "Mid-West (NUTS 2013)": "Galway",
    "South-East (NUTS 2013)": "Waterford Ireland",
    "South-West (NUTS 2013)": "Killarney, Ireland",
    "Kalymnos, Karpathos, Kasos, Kos, Rodos": "Kalymnos Greece",
    "Andros, Thira, Kea, Milos, Mykonos, Naxos, Paros, Syros, Tinos": "Andros Greece",
    "Gozo and Comino/Ghawdex u Kemmuna": "Malta",
    "Ave (NUTS 2010)": "Aveiro, Aveiro, Portugal",
    "Inner London - West (NUTS 2010)": "Hyde Park",
    "Inner London - East (NUTS 2010)": "Tower Hamlets",
    "Outer London - East and North East (NUTS 2010)": "Barking and Dagenham",
    "Outer London - South (NUTS 2010)": "Croydon",
    "Outer London - West and North West (NUTS 2010)": "Harrow",
    "Osrednjeslovenska (NUTS 2010)": "Ljubljana",
    "Aitoloakarnania (NUTS 2010)": "Agrinio",
    "Bodenseekreis": "Uberlingen",
    "Donnersbergkreis": "Kirchheimbolanden",
    "Erzgebirgskreis": "Annaberg-Buchholz",
    "Fthiotida (NUTS 2010)": "Lamia",
    "Hochsauerlandkreis": "Meschede",
    "Hochtaunuskreis": "Bad Homburg",
    "Kyffhäuserkreis": "Sondershausen",
    "Mittelburgenland": "Oberpullendorf",
    "Mittelsachsen": "Freiberg",
    "Nordburgenland": "Eisenstadt",
    "Nordsachsen": "Torgau",
    "Nordvorpommern (NUTS 2010)": "Stralsund",
    "Nordwestmecklenburg (NUTS 2010)": "Wismar",
    "Oberkärnten": "Spittal an der Drau",
    "Odenwaldkreis": "Eberbach",
    "Ortenaukreis": "Offenburg",
    "Ostalbkreis": "Aalen",
    "Østsjælland": "Roskilde",
    "Oststeiermark": "Graz",
    "Ostvorpommern (NUTS 2010)": "Greifswald",
    "Saalekreis": "Halle",
    "Salzlandkreis": "Bernburg",
    "Spodnjeposavska (NUTS 2010)": "Krsko",
    "Südburgenland": "Oberwart",
    "Traunviertel": "Linz",
    "Unterallgäu": "Mindelheim",
    "Unterkärnten": "Klagenfurt",
    "Vestjylland": "Ringkobing",
    "Vogelsbergkreis": "Lauterbach",
    "Vogtlandkreis": "Plauen",
    "Wartburgkreis": "Eisenach",
    "Westerwaldkreis": "Montabaur",
    "Westliche Obersteiermark": "Leoben",
    "Zollernalbkreis": "Albstadt",
    "Gorenjska (NUTS 2010)": "Kranj",
    "Bjelovarsko-bilogorska zupanija": "Bjelovar",
    "Viroviticko-podravska zupanija": "Virovitica",
    "Pozesko-slavonska zupanija": "Požega",
    "Brodsko-posavska zupanija": "Slavonski Brod",
    "Osjecko-baranjska zupanija": "Osijek",
    "Vukovarsko-srijemska zupanija": "Vukovar",
    "Karlovacka zupanija": "Karlovac",
    "Sisacko-moslavacka zupanija": "Sisak",
    "Primorsko-goranska zupanija": "Rijeka",
    "Licko-senjska zupanija": "Gospić",
    "Zadarska zupanija": "Zadar",
    "Sibensko-kninska zupanija": "Šibenik",
    "Splitsko-dalmatinska zupanija": "Split",
    "Istarska zupanija": "Pula",
    "Dubrovacko-neretvanska zupanija": "Dubrovnik",
    "Grad Zagreb": "Zagreb",
    "Medimurska zupanija": "Cakovec",
    "Varazdinska zupanija": "Varaždin",
    "Koprivnicko-krizevacka zupanija": "Koprivnica",
    "Krapinsko-zagorska zupanija": "Krapina",
    "Zagrebacka zupanija": "Zagreb",
    "Kainuu (NUTS 2013)": "Kajaani",
    "Kesk-Eesti (NUTS 2016)": "Tartu",
    "Kirde-Eesti (NUTS 2016)": "Johvi",
    "Pohjois-Pohjanmaa (NUTS 2013)": "Oulu",
    "Sofia (stolitsa)": "Sofia",
    "Blagoevgrad": "Blagoevgrad",
    "Burgas": "Burgas",
    "Dobrich": "Dobrich",
    "Etelä-Karjala": "Lappeenranta",
    "Etelä-Pohjanmaa": "Seinäjoki",
    "Etelä-Savo": "Mikkeli",
    "Gabrovo": "Gabrovo",
    "Haskovo": "Haskovo",
    "Helsinki-Uusimaa": "Helsinki",
    "Kanta-Häme": "Hämeenlinna",
    "Kardzhali": "Kardzhali",
    "Keski-Pohjanmaa": "Kokkola",
    "Keski-Suomi": "Jyväskylä",
    "Kymenlaakso": "Kotka",
    "Kyustendil": "Kyustendil",
    "Lappi": "Rovaniemi",
    "Lovech": "Lovech",
    "Lääne-Eesti": "Pärnu",
    "Lõuna-Eesti": "Tartu",
    "Montana": "Montana",
    "Pazardzhik": "Pazardzhik",
    "Pernik": "Pernik",
    "Pirkanmaa": "Tampere",
    "Pleven": "Pleven",
    "Plovdiv": "Plovdiv",
    "Pohjanmaa": "Vaasa",
    "Pohjois-Karjala": "Joensuu",
    "Pohjois-Savo": "Kuopio",
    "Päijät-Häme": "Lahti",
    "Põhja-Eesti": "Tallinn",
    "Razgrad": "Razgrad",
    "Ruse": "Ruse",
    "Satakunta": "Pori",
    "Shumen": "Shumen",
    "Silistra": "Silistra",
    "Sliven": "Sliven",
    "Smolyan": "Smolyan",
    "Stara Zagora": "Stara Zagora",
    "Targovishte": "Targovishte",
    "Varna": "Varna",
    "Varsinais-Suomi": "Turku",
    "Veliko Tarnovo": "Veliko Tarnovo",
    "Vidin": "Vidin",
    "Vratsa": "Vratsa",
    "Yambol": "Yambol",
    "Åland": "Mariehamn",
}

WEATHER_COUNTRY_CODE_TRANSFORMATIONS = {
    "BE": "Belgium",
    "BU": "Bulgaria",
    "CZ": "Czech Republic",
    "DK": "Denmark",
    "DE": "Germany",
    "ES": "Spain",
    "EE": "Estonia",
    "FI": "Finland",
    "HR": "Croatia",
    "IE": "Ireland",
    "EL": "Greece",
    "FR": "France",
    "IT": "Italy",
    "CY": "Cyprus",
    "LV": "Latvia",
    "LT": "Lithuania",
    "LU": "Luxembourg",
    "HU": "Hungary",
    "MT": "Malta",
    "NL": "Netherlands",
    "AT": "Austria",
    "PL": "Poland",
    "PT": "Portugal",
    "RO": "Romania",
    "SI": "Slovenia",
    "SK": "Slovakia",
    "FL": "Finland",
    "SE": "Sweden",
    "IS": "Iceland",
    "LI": "Liechtenstein",
    "NO": "Norway",
    "CH": "Switzerland",
    "GB": "England",
}
