"""Config file for the sampler module."""

GAUSSIAN_SAMPLED_FEATURES = [
    "USEFUL FLOOR AREA (m2)",
    "GROUND FLOOR AREA (m2)",
    "WALL AREA (m2)",
    "WINDOW AREA (m2)",
    "ROOF AREA (m2)",
    "FLOOR MATERIAL THICKNESS (m)",
    "FLOOR MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "FLOOR MATERIAL DENSITY (kg/m3)",
    "FLOOR MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "FLOOR INSULATION MATERIAL THICKNESS (m)",
    "FLOOR INSULATION MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "FLOOR INSULATION MATERIAL DENSITY (kg/m3)",
    "FLOOR INSULATION MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "FLOOR U-VALUE (W/m2/K)",
    "WALL MATERIAL THICKNESS (m)",
    "WALL MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "WALL MATERIAL DENSITY (kg/m3)",
    "WALL MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "WALL INSULATION MATERIAL THICKNESS (m)",
    "WALL INSULATION MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "WALL INSULATION MATERIAL DENSITY (kg/m3)",
    "WALL INSULATION MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "WALL U-VALUE (W/m2/K)",
    "WINDOW U-VALUE (W/m2/K)",
    "ROOF MATERIAL THICKNESS (m)",
    "ROOF MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "ROOF MATERIAL DENSITY (kg/m3)",
    "ROOF MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "ROOF INSULATION MATERIAL THICKNESS (m)",
    "ROOF INSULATION MATERIAL THERMAL CONDUCTIVITY (W/m/K)",
    "ROOF INSULATION MATERIAL DENSITY (kg/m3)",
    "ROOF INSULATION MATERIAL SPECIFIC HEAT CAPACITY (J/kg/K)",
    "ROOF U-VALUE (W/m2/K)",
    "HEATING SYSTEM 1 EFFICIENCY",
    "HEATING SYSTEM 2 EFFICIENCY",
    "HEATING SYSTEM 3 EFFICIENCY",
    "DHW SYSTEM 1 EFFICIENCY",
    "DHW SYSTEM 2 EFFICIENCY",
    "DHW SYSTEM 3 EFFICIENCY",
    "AIR INFILTRATION",
    "SOLAR PV PANEL EFFICIENCY",
    "SOLAR PV ACTIVE AREA FRACTION",
]

GAUSSIAN_NOISE_STD_DEV_PARAMETER = 0.2  # 20% of the mean

BETA_SAMPLED_FEATURES = [
    "BEV MINIMUM BATTERY SIZE (kWh)",
    "BEV MAXIMUM BATTERY SIZE (kWh)",
    "PHEV MINIMUM BATTERY SIZE (kWh)",
    "PHEV MAXIMUM BATTERY SIZE (kWh)",
]

BETA_PARAMETERS = {
    "BEV ALPHA": 3,
    "BEV BETA": 6,
    "PHEV ALPHA": 3,
    "PHEV BETA": 6,
}
