name: "dt"

batch_size: 512
learning_steps: 4000
discretisation_bins: 1024
context_length: 32

# transformer
number_of_blocks: 8
number_of_heads: 8
embedding_dimension: 512
dropout: 0.1
layer_norm_epsilon: 1e-6
feedforward_hidden_dimension: 1024
activation: 'gelu'
key_value_size: 32

# output pooler
pooler_hidden_dim: 1024

# tokenizer
tokenizer_mu: 100

# optimiser
betas: [0.9, 0.95]
optimiser_epsilon: 1e-8
learning_rate: 1e-5
weight_decay: 0.1
gradient_norm_clip: 1.0

# positional encoding
positional_encoder_table_dimension: 128 # set to a larger value that an observation dim
